# Generated by Django 5.1.3 on 2024-11-23 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_desc', models.TextField(max_length=1500)),
                ('pro_img', models.CharField(max_length=255)),
                ('pro_rep', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_link', models.URLField(blank=True, max_length=255, null=True)),
                ('pined', models.BooleanField(default=False)),
                ('pro_cr_date', models.DateTimeField(auto_now_add=True)),
                ('pro_up_date', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='proIDUs', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'PROJECTS',
            },
        ),
    ]
