# Generated by Django 5.1.3 on 2024-11-23 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_pined_alter_project_pro_cr_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_name',
            field=models.CharField(error_messages={'null': 'The project name field cannot be null.'}, help_text='Project name.', max_length=100, validators=[django.core.validators.MaxLengthValidator(100, message='Name too long'), django.core.validators.RegexValidator('^[a-zA-Z0-9.\\-() ]*$', 'Only letters, numbers, hyphens, periods, parentheses, and spaces are allowed')], verbose_name='Project name'),
        ),
    ]
