# Generated by Django 5.1.3 on 2024-11-23 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_pro_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_link',
            field=models.CharField(blank=True, help_text='Project link.', max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255, message='URL too long'), django.core.validators.RegexValidator(message='No spaces allowed', regex='^\\S+$')], verbose_name='Link'),
        ),
    ]
