# Generated by Django 5.1.3 on 2024-11-23 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='us_phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato '+[Prefijo] [Numero de telefono].", regex='^\\+\\d{1,3} \\d{1,14}$')]),
        ),
    ]
