# Generated by Django 5.1.3 on 2024-11-23 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_alter_usuario_us_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='us_br_date',
            field=models.DateField(validators=[django.core.validators.RegexValidator(message="La fecha de nacimiento debe estar en el formato 'YYYY-MM-DD'.", regex='^\\d{4}-\\d{2}-\\d{2}$')], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_fr_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, acentos y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚ ]+$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_ls_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='El apellido solo puede contener letras, acentos y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚ ]+$')]),
        ),
    ]
