# Generated by Django 5.1.3 on 2024-11-23 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0003_alter_usuario_us_br_date_alter_usuario_us_fr_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_us',
            field=models.AutoField(help_text='User ID.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the user is active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indicates if the user is a staff member.', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_br_date',
            field=models.DateField(error_messages={'blank': 'Birth date cannot be blank.', 'null': 'Birth date cannot be null.'}, help_text="User's birth date.", validators=[django.core.validators.RegexValidator(message="Birth date must be in the format 'YYYY-MM-DD'.", regex='^\\d{4}-\\d{2}-\\d{2}$')], verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_cr_date',
            field=models.DateTimeField(auto_now_add=True, help_text="User's creation date and time.", validators=[django.core.validators.RegexValidator(message='Invalid date and time format. Use YYYY-MM-DD HH:MM:SS', regex='^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$')], verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_email',
            field=models.EmailField(error_messages={'blank': 'Email cannot be blank.', 'null': 'Email cannot be null.'}, help_text="User's email address.", max_length=254, unique=True, validators=[django.core.validators.MaxLengthValidator(255, 'Email is too long.'), django.core.validators.RegexValidator('^.+@.+\\..+$', 'Invalid email address.')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_fr_name',
            field=models.CharField(error_messages={'blank': 'First name cannot be blank.', 'null': 'First name cannot be null.'}, help_text="User's first name.", max_length=30, validators=[django.core.validators.RegexValidator(message='First name can only contain letters, accents, and spaces.', regex='^[a-zA-ZáéíóúÁÉÍÓÚ ]+$')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_ls_name',
            field=models.CharField(blank=True, help_text="User's last name.", max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Last name can only contain letters, accents, and spaces.', regex='^[a-zA-ZáéíóúÁÉÍÓÚ ]+$')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_phone',
            field=models.CharField(error_messages={'blank': 'Phone number cannot be blank.', 'null': 'Phone number cannot be null.'}, help_text="User's phone number.", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+[Prefix] [Phone number].", regex='^\\+\\d{1,3} \\d{1,14}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_photo',
            field=models.CharField(blank=True, default='static/users/placeholder.jpg', help_text="URL of the user's profile photo.", max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255, 'Photo URL is too long.')], verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_up_date',
            field=models.DateTimeField(blank=True, help_text="User's last update date and time.", null=True, validators=[django.core.validators.RegexValidator(message='Invalid date and time format. Use YYYY-MM-DD HH:MM:SS', regex='^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$')], verbose_name='Update Date'),
        ),
    ]
