# Generated by Django 5.1.3 on 2024-11-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0004_alter_usuario_options_alter_usuario_id_us_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_us',
            new_name='id',
        ),
    ]
