# Generated by Django 5.1.3 on 2024-11-25 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0005_rename_id_us_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='us_cv',
            field=models.CharField(blank=True, help_text="URL of the user's CV.", max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255, 'CV URL is too long.')], verbose_name='CV'),
        ),
    ]
