# Generated by Django 5.1.3 on 2024-11-23 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(db_column='ptIDPro', on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('tool', models.ForeignKey(db_column='ptIDTl', on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
            options={
                'verbose_name': 'Project Tool',
                'verbose_name_plural': 'Project Tools',
                'db_table': 'PROJECT_TOOLS',
            },
        ),
    ]
