# Generated by Django 5.1.3 on 2024-11-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_pro_link'),
        ('projectsTools', '0002_alter_projecttool_project_alter_projecttool_tool'),
        ('tools', '0002_alter_tool_tl_name_alter_tool_tl_tool'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttool',
            unique_together={('tool', 'project')},
        ),
    ]
