# Generated by Django 5.1.3 on 2024-11-23 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab_desc', models.TextField(blank=True, max_length=1500, null=True)),
                ('ab_hero', models.CharField(blank=True, max_length=100, null=True)),
                ('ab_wk_status', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(db_column='abIDUs', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'db_table': 'ABOUT',
            },
        ),
    ]
