# Generated by Django 5.1.3 on 2024-11-23 02:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='ab_desc',
            field=models.TextField(blank=True, error_messages={'null': 'The description cannot be empty.'}, help_text='User description.', max_length=1500, null=True, validators=[django.core.validators.MaxLengthValidator(1500, message='Description too long')], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='ab_hero',
            field=models.CharField(blank=True, error_messages={'null': 'The hero cannot be empty.'}, help_text="User's hero.", max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100, message='Name too long')], verbose_name='Hero'),
        ),
        migrations.AlterField(
            model_name='about',
            name='ab_wk_status',
            field=models.BooleanField(default=True, error_messages={'null': 'The work status cannot be empty.'}, help_text="User's work status.", validators=[django.core.validators.MaxLengthValidator(1, message='Value not allowed'), django.core.validators.RegexValidator(message='Value not allowed', regex='^[01]$')], verbose_name='Work status'),
        ),
        migrations.AlterField(
            model_name='about',
            name='usuario',
            field=models.OneToOneField(db_column='abIDUs', error_messages={'invalid': 'Invalid user.', 'null': 'The user field cannot be empty.', 'unique': 'This user already has an entry in About.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
