# Generated by Django 5.1.3 on 2024-11-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_ab_desc_alter_about_ab_hero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='ab_desc',
            field=models.TextField(blank=True, error_messages={'null': 'The description cannot be empty.'}, help_text='User description.', max_length=1500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='ab_hero',
            field=models.CharField(blank=True, error_messages={'null': 'The hero cannot be empty.'}, help_text="User's hero.", max_length=100, null=True, verbose_name='Hero'),
        ),
        migrations.AlterField(
            model_name='about',
            name='ab_wk_status',
            field=models.BooleanField(default=True, error_messages={'null': 'The work status cannot be empty.'}, help_text="User's work status.", verbose_name='Work status'),
        ),
    ]
