# Generated by Django 5.1.3 on 2024-11-23 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_social_options_alter_social_sc_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='sc_link',
            field=models.CharField(error_messages={'blank': 'The Social Network Link field cannot be blank.', 'null': 'The Social Network Link field cannot be empty.'}, help_text='Link to the social network.', max_length=250, unique=True, validators=[django.core.validators.MaxLengthValidator(250, message='URL too long'), django.core.validators.RegexValidator('^\\S+$', message='Spaces are not allowed')], verbose_name='Social Network Link'),
        ),
    ]
