# Generated by Django 5.1.3 on 2024-11-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id_tl', models.AutoField(primary_key=True, serialize=False)),
                ('tl_name', models.CharField(max_length=50, unique=True)),
                ('tl_tool', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'db_table': 'TOOLS',
            },
        ),
    ]
