# Generated by Django 5.1.3 on 2024-11-23 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tl_name',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.', 'null': 'This field cannot be null.'}, help_text='Tool name.', max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50, message='Name too long'), django.core.validators.RegexValidator('^[a-zA-Z0-9.-]*$', 'Only letters, numbers, hyphens, and periods are allowed')], verbose_name='Tool name'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tl_tool',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.', 'null': 'This field cannot be null.'}, help_text='Tool link.', max_length=255, unique=True, validators=[django.core.validators.MaxLengthValidator(255, message='URL too long'), django.core.validators.RegexValidator('^\\S+$', 'No spaces allowed')], verbose_name='Tool link'),
        ),
    ]
